// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Seatly1.Models;

public partial class CollectionItem
{
    public int SerialId { get; set; }

    public string UserId { get; set; }

    public string ActivityId { get; set; }
}