// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Seatly1.Models;

public partial class DailyCheckIn
{
    public int Id { get; set; }

    public int? MemberId { get; set; }

    public DateOnly? CheckInTime { get; set; }
}