// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Seatly1.Models;

public partial class Organizer
{
    public int OrganizerId { get; set; }

    public string? OrganizerAccount { get; set; }

    public string? LoginPassword { get; set; }

    public string? OrganizerName { get; set; }

    public string? OrganizerCategory { get; set; }

    public string? OrganizerPhoto { get; set; }

    public string? Menu { get; set; }

    public string? Address { get; set; }

    public string? ReservationUrl { get; set; }

    public string? Hashtag { get; set; }

    public string? Email { get; set; }

    public string? Phone { get; set; }

    public bool? Validation { get; set; }
}
